# Generated by Django 5.2.8 on 2026-03-03 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created'], 'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='skill',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='skill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé logiquement'),
        ),
        migrations.AddField(
            model_name='skill',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='URL GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, verbose_name='URL Live'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma separated tags', max_length=200, verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(help_text='Lucide or FontAwesome icon name', max_length=50, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=80, help_text='Percentage 0-100', verbose_name='Maîtrise'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.category', verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du site/entreprise')),
                ('logo', models.ImageField(upload_to='settings/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Favicon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('bio_title', models.CharField(blank=True, max_length=200, verbose_name='Titre Bio')),
                ('bio_text', models.TextField(blank=True, verbose_name='Texte Bio')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Curriculum Vitae')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('position', models.CharField(max_length=200, verbose_name='Poste')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('description', models.TextField(verbose_name='Description')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(help_text="Nom de l'icône (Lucide, Lucide, FontAwesome)", max_length=50, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', '-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé logiquement')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('position', models.CharField(max_length=100, verbose_name='Poste/Entreprise')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Avatar')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
