from django.test import TestCase
from django.utils.text import slugify

from .models import Category, Project, Tag, Post


class SlugGenerationTests(TestCase):
    def test_category_slug_autogenerated(self):
        cat = Category.objects.create(name="My Category")
        self.assertEqual(cat.slug, slugify(cat.name))

        # duplicate name should append suffix
        cat2 = Category.objects.create(name="My Category")
        self.assertNotEqual(cat2.slug, cat.slug)
        self.assertTrue(cat2.slug.startswith(slugify(cat2.name)))

    def test_project_slug_autogenerated(self):
        project = Project.objects.create(title="Demo Project", description="", tech_stack="")
        self.assertEqual(project.slug, slugify(project.title))

        project2 = Project.objects.create(title="Demo Project", description="", tech_stack="")
        self.assertNotEqual(project2.slug, project.slug)

    def test_tag_slug_autogenerated(self):
        tag = Tag.objects.create(name="Django")
        self.assertEqual(tag.slug, slugify(tag.name))

    def test_post_slug_autogenerated(self):
        post = Post.objects.create(title="Hello World", featured_image="blog/placeholder.jpg", content="Test", excerpt="",)
        self.assertEqual(post.slug, slugify(post.title))
